"""Create the base migration

Revision ID: 0101f367cf23
Revises: 
Create Date: 2025-02-21 14:15:30.576427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0101f367cf23'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('pacients', sa.Column('weight', sa.Float(), nullable=True))
    # op.drop_column('pacients', 'weigth')
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('pacients', sa.Column('weigth', sa.FLOAT(), nullable=True))
    # op.drop_column('pacients', 'weight')
    # ### end Alembic commands ###
